/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Bets {
  btc_price: Numeric;
  created_at: Generated<Timestamp>;
  direction: string;
  id: Generated<number>;
  last_checked_at: Timestamp | null;
  status: string;
  updated_at: Generated<Timestamp>;
  user_id: number;
}

export interface Schemaversion {
  md5: string | null;
  name: string | null;
  run_at: Timestamp | null;
  version: Int8;
}

export interface Users {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  score: Generated<number>;
  updated_at: Generated<Timestamp>;
  username: string;
}

export interface DB {
  bets: Bets;
  schemaversion: Schemaversion;
  users: Users;
}
