services:
  updown-test-db:
    image: postgres:14.4-alpine
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c random_page_cost=1.0
    restart: unless-stopped
    ports:
      - 5434:5432
    tmpfs: /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: updown
      PGDATA: /var/lib/postgresql/data/pgdata
    container_name: updown-test-db
